[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.34"
memory_limit = 43554432
gas_limit = 9223372036854775807
gas_price = 0
optimizer = true
optimizer_runs = 10000
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "registry-contracts/=lib/registry-contracts/",
    "protocol-contracts/=lib/protocol-contracts/",
    "solmate/=lib/solmate/src/",
]

fs_permissions = [{ access = "read-write", path = "./deployments" }]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.34"
optimizer = true
optimizer_runs = 10000
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "registry-contracts/=lib/registry-contracts/",
    "protocol-contracts/=lib/protocol-contracts/",
    "solmate/=lib/solmate/src/",
]

fs_permissions = [{ access = "read-write", path = "./deployments" }]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
