name: CI

on:
  push:
  pull_request_target:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          # For pull_request_target events, checkout the pr's repository code
          # Otherwise use the default behavior
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
          repository: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install forge-std
        run: forge install foundry-rs/forge-std

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
        run: |
          forge test -vvv
        id: test

      - name: Run Forge coverage
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          LCOV_FILE: ./${{ github.sha }}-lcov.info
        run: |
          forge coverage --no-cache --ir-minimum --no-match-coverage 'test|node_modules|script|src/libs' --report lcov --lcov-version '5.2.0' -r $LCOV_FILE
          cat $LCOV_FILE
        id: coverage

      - uses: codecov/codecov-action@v5
        env:
          LCOV_FILE: ./${{ github.sha }}-lcov.info
        with:
          fail_ci_if_error: true
          files: ${{ env.LCOV_FILE }}
          token: ${{ secrets.CODECOV_TOKEN }}
